/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Ferdynand Monroy 9959 24 14049 
//creacion de examen final junio 01 del 2026

package Vista.Final;

import Controlador.clsUsuarioConectado;
//import Modelo.PermisosDAO;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import Controlador.Final.clsCarreras;
import Modelo.BitacoraDAO;
import Modelo.Conexion;
import Modelo.Final.CarrerasDAO;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author macoh
 */
public class frmCarreras extends javax.swing.JInternalFrame {
private DefaultTableModel modeloCarreras;

    public frmCarreras() {
        initComponents();
        
        txtIcarrera.setEditable(false);
       
    txtIcarrera.setEnabled(false);  
      modeloCarreras = new DefaultTableModel(
            new Object[]{"ID Carrera", "Nombre carrera", "ID Facultado", "Estado carrera"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tablaCarreras.setModel(modeloCarreras);
        actualizarTabla();
        cargarPermisos();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
    }
    public void cargarPermisos() {
        int usuId = clsUsuarioConectado.getUsuId();
        //PermisosDAO permisosDAO = new PermisosDAO();
        int codigoAplicacion = 2000; 
        //btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarreras = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        label15 = new javax.swing.JLabel();
        txtfacultad = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        label16 = new javax.swing.JLabel();
        txtInombre = new javax.swing.JTextField();
        label17 = new javax.swing.JLabel();
        txtIcarrera = new javax.swing.JTextField();
        label19 = new javax.swing.JLabel();
        label18 = new javax.swing.JLabel();
        txtfacultad1 = new javax.swing.JTextField();
        label20 = new javax.swing.JLabel();
        txtlestado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(782, 736));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        tablaCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID carrera", "Nombre carrera", "ID Facultad", "Estado carrera"
            }
        ));
        tablaCarreras.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaCarrerasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCarrerasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCarreras);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 340, 692, 300);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Carreras");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 20, 160, 25);

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Trasnsporte", "ID Empleado", "Tipo de Vehiculo" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cboxTipoBusqueda);
        cboxTipoBusqueda.setBounds(10, 30, 139, 26);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(10, 70, 110, 26);

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(130, 70, 72, 27);

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("ID Facultad");
        getContentPane().add(label15);
        label15.setBounds(20, 220, 84, 16);

        txtfacultad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtfacultad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtfacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacultadActionPerformed(evt);
            }
        });
        getContentPane().add(txtfacultad);
        txtfacultad.setBounds(120, 220, 170, 17);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(430, 140, 90, 30);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(430, 170, 90, 30);

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda);
        btnAyuda.setBounds(600, 220, 72, 23);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(340, 200, 90, 23);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(340, 140, 90, 23);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(340, 170, 90, 23);

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes);
        btnReportes.setBounds(520, 220, 76, 23);

        label16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label16.setText("ID Carrera");
        getContentPane().add(label16);
        label16.setBounds(20, 140, 80, 16);

        txtInombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtInombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtInombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtInombre);
        txtInombre.setBounds(120, 180, 170, 17);

        label17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label17.setText("Nombre");
        getContentPane().add(label17);
        label17.setBounds(20, 180, 90, 16);

        txtIcarrera.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIcarrera.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtIcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcarreraActionPerformed(evt);
            }
        });
        getContentPane().add(txtIcarrera);
        txtIcarrera.setBounds(120, 140, 170, 17);

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("*Dar doble click a la fila deseada");
        getContentPane().add(label19);
        label19.setBounds(10, 310, 196, 16);

        label18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label18.setText("ID Facultad");
        getContentPane().add(label18);
        label18.setBounds(20, 220, 84, 16);

        txtfacultad1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtfacultad1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtfacultad1);
        txtfacultad1.setBounds(120, 220, 170, 17);

        label20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label20.setText("Estado");
        getContentPane().add(label20);
        label20.setBounds(20, 260, 84, 16);

        txtlestado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtlestado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtlestado);
        txtlestado.setBounds(120, 260, 170, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCarrerasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaCarrerasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaCarrerasAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed

        txtBuscar.setText("");
        txtBuscar.requestFocus();
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
        switch (seleccion) {
            case "ID Movimiento":
            buscarPorID();
            break;
            case "Tipo de Movimiento":
            buscarPorNombre();
            break;
            case "Producto":
            buscarPorTipoVehiculo();
            break;
   
        }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String filtro = txtBuscar.getText().trim().toLowerCase();
        String criterio = cboxTipoBusqueda.getSelectedItem().toString();
        boolean encontrado = false;

        if (filtro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar.");
            return;
        }
        int columna = 0;
        if (criterio.equals("ID Movimiento")) columna = 0;
        else if (criterio.equals("Tipo de Movimiento")) columna = 1;
        else if (criterio.equals("Producto")) columna = 2;
        else if (criterio.equals("Fecha")) columna = 3;

        for (int i = 0; i < tablaCarreras.getRowCount(); i++) {
            String valorCelda = tablaCarreras.getValueAt(i, columna).toString().toLowerCase();

            if (valorCelda.contains(filtro)) {
                tablaCarreras.setRowSelectionInterval(i, i);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró coincidencia para: " + filtro);
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String filtro = txtBuscar.getText().trim();

TableRowSorter<DefaultTableModel> sorter =
        new TableRowSorter<>(
                (DefaultTableModel) tablaCarreras.getModel()
        );

tablaCarreras.setRowSorter(sorter);

if (filtro.length() == 0) {

    sorter.setRowFilter(null);

} else {

    int seleccion = cboxTipoBusqueda.getSelectedIndex();
    int indiceColumna = 0;

    if (seleccion == 0) {

        indiceColumna = 0;

    } else if (seleccion == 1) {

        indiceColumna = 1;

    } else if (seleccion == 2) {

        indiceColumna = 2;

    } else {

        indiceColumna = 0;
    }

    try {

        sorter.setRowFilter(
                RowFilter.regexFilter(
                        "(?i)" + filtro,
                        indiceColumna
                )
        );

        if (tablaCarreras.getRowCount() == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontraron resultados."
            );
        }

        // ================= BITACORA =================

        try {

            int idUsuario =
                    clsUsuarioConectado.getUsuId();

            int aplCodigo = 2000;

            BitacoraDAO bitacoraDAO =
                    new BitacoraDAO();

            bitacoraDAO.insert(
                    idUsuario,
                    aplCodigo,
                    "Consulta transportista ID " + filtro
            );

        } catch (Exception ex) {

            System.out.println(
                    "Error bitácora consulta: "
                    + ex.getMessage()
            );
        }

        // ============================================

    } catch (Exception e) {

        System.err.println(
                "Error en el filtro: "
                + e.getMessage()
        );
    }
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
// LIMPIAR TODOS LOS CAMPOS DEL FORMULARIO
// 🔴 SI AGREGAS NUEVO CAMPO → limpiar aquí también

txtfacultad.setText(""); // campo texto
txtInombre.setText("");   // campo numérico
txtIcarrera.setText(""); // ID (PK)

// BLOQUEAR ID (no editable)
txtIcarrera.setEditable(false);
txtIcarrera.setEnabled(false);   

tablaCarreras.clearSelection(); // quitar selección tabla

cboxTipoBusqueda.setSelectedIndex(0); // reset combo
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
// QUITAR FILTROS DE TABLA SI EXISTEN
if (tablaCarreras.getRowSorter() != null) {
    tablaCarreras.setRowSorter(null);
}

// LIMPIAR BUSCADOR
txtBuscar.setText("");

// RESET COMBO
cboxTipoBusqueda.setSelectedIndex(0);

// LIMPIAR CAMPOS
txtfacultad.setText("");
txtIcarrera.setText("");
txtInombre.setText("");

// BLOQUEAR ID
txtIcarrera.setEditable(false); 

tablaCarreras.clearSelection();

// 🔴 RECARGAR DATOS DESDE BD
actualizarTabla(); 

JOptionPane.showMessageDialog(this, 
    "Formulario e interfaz restablecidos correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        //Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();

        //ventanaAyuda.setVisible(true);
        //ventanaAyuda.setLocationRelativeTo(null);
        //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Documents\\ayudaFinal\\ayuda.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int fila = tablaCarreras.getSelectedRow();

if (fila != -1) {

    String codigo = tablaCarreras.getValueAt(fila, 0).toString();

    Modelo.Final.CarrerasDAO dao = new Modelo.Final.CarrerasDAO();

    if (dao.eliminar(codigo)) {

        actualizarTabla();
        btnLimpiarActionPerformed(null);

        JOptionPane.showMessageDialog(this, "Eliminado correctamente");

    } else {
        JOptionPane.showMessageDialog(this, "Error al eliminar");
    }

} else {
    JOptionPane.showMessageDialog(this, "Seleccione una fila");
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

         System.out.println("Entró al botón");

    if (txtInombre.getText().trim().isEmpty() ||
        txtfacultad.getText().trim().isEmpty() ||
        txtlestado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Complete los campos obligatorios");
        return;
    }

    try {

        // 🔥 CREAR OBJETO
        Controlador.Final.clsCarreras obj = new Controlador.Final.clsCarreras();

        obj.setNombreCarrera(txtInombre.getText().trim());
        obj.setCodigoFacultad(txtfacultad.getText().trim());
        obj.setEstatusCarrera(txtlestado.getText().trim());

        // 🔥 DAO
        Modelo.Final.CarrerasDAO dao = new Modelo.Final.CarrerasDAO();

        if (dao.insertar(obj)) {

            JOptionPane.showMessageDialog(this, "Registrado correctamente");
            actualizarTabla();
            btnLimpiarActionPerformed(null);

        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
// VALIDACIÓN → debe existir un ID seleccionado (doble click)
if (txtIcarrera.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Seleccione un registro.");
    return;
}

try {

    Controlador.Final.clsCarreras obj = new Controlador.Final.clsCarreras();

    obj.setCodigoCarrera(Integer.parseInt(txtIcarrera.getText()));
    obj.setNombreCarrera(txtInombre.getText().trim());
    obj.setCodigoFacultad(txtfacultad.getText().trim());
    obj.setEstatusCarrera(txtlestado.getText().trim());

    Modelo.Final.CarrerasDAO dao = new Modelo.Final.CarrerasDAO();

    if (dao.actualizar(obj)) {

        actualizarTabla();
        JOptionPane.showMessageDialog(this, "Actualizado correctamente");
        btnLimpiarActionPerformed(null);

    } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        //Connection conn = null;
    //Map p = new HashMap();
    //net.sf.jasperreports.engine.JasperReport report;
    //JasperPrint print;
        try {
            //conn = Conexion.getConnection();
            //report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                //+ "/src/main/java/Reportes/rFinal.jrxml");
                //print = JasperFillManager.fillReport(report, p, conn);
            //JasperViewer view = new JasperViewer(print, false);
                //view.setTitle("Reporte");
            //view.setVisible(true);
        } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnReportesActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void tablaCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCarrerasMouseClicked

     if (evt.getClickCount() == 2) {

    int filaVisual = tablaCarreras.getSelectedRow();

    if (filaVisual != -1) {

        int filaModelo = tablaCarreras.convertRowIndexToModel(filaVisual);

        txtIcarrera.setText(modeloCarreras.getValueAt(filaModelo, 0).toString());
        txtInombre.setText(modeloCarreras.getValueAt(filaModelo, 1).toString());
        txtfacultad.setText(modeloCarreras.getValueAt(filaModelo, 2).toString());
        txtlestado.setText(modeloCarreras.getValueAt(filaModelo, 3).toString());

        txtIcarrera.setEditable(false);
    }
}
    }//GEN-LAST:event_tablaCarrerasMouseClicked

    private void txtIcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIcarreraActionPerformed

    private void txtInombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInombreActionPerformed

    private void txtfacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacultadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmCarreras().setVisible(true));
    }
    
    
    private void buscarPorID() {
        System.out.println("Buscando por ID...");
      
    }

    private void buscarPorNombre() {
        System.out.println("Buscando por Nombre...");
    }

    private void buscarPorTipoVehiculo() {
        System.out.println("Buscando por Vehiculo...");
    }

  
    
   public void actualizarTabla() {
    // Crear instancia del DAO (conexión con la BD)
    Modelo.Final.CarrerasDAO dao = new Modelo.Final.CarrerasDAO();

    List<Controlador.Final.clsCarreras> lista = dao.listar();

    modeloCarreras.setRowCount(0);

    for (Controlador.Final.clsCarreras c : lista) {

        modeloCarreras.addRow(new Object[]{
            c.getCodigoCarrera(),     // 0
            c.getNombreCarrera(),     // 1
            c.getCodigoFacultad(),    // 2
            c.getEstatusCarrera()     // 3
        });
    }
}
   
 
  
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label20;
    private javax.swing.JTable tablaCarreras;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIcarrera;
    private javax.swing.JTextField txtInombre;
    private javax.swing.JTextField txtfacultad;
    private javax.swing.JTextField txtfacultad1;
    private javax.swing.JTextField txtlestado;
    // End of variables declaration//GEN-END:variables
}
